/** Same-origin iframe script for one explicitly requested page inspection. */
import type { LabelStudioInspectionProtocol } from '@deepseek-ai/dsh-label-studio-protocol';
/** Fixed same-origin URL served only by the frame proxy. */
export declare const LABEL_STUDIO_FRAME_BRIDGE_PATH = "/.dsh/label-studio-page-bridge.js";
/**
 * Add one external bridge script to an HTML document.
 * @param html - decoded Label Studio HTML.
 * @param protocol - protocol version represented by the script route.
 * @returns HTML referencing the same-origin bridge script exactly once.
 */
export declare function injectLabelStudioInspectionBridge(html: string, protocol: LabelStudioInspectionProtocol): string;
/**
 * Render the isolated classic script served inside the Label Studio origin.
 * @param protocol - exact parent/iframe wire protocol.
 * @param capability - ephemeral frame capability generated by the proxy.
 * @returns JavaScript with one message listener and no passive instrumentation.
 */
export declare function renderLabelStudioFrameBridgeScript(protocol: LabelStudioInspectionProtocol, capability: string): string;
//# sourceMappingURL=frame-bridge-script.d.ts.map